workflows:
  betifizz-workflow:
    name: BetiFizz
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: BetiFizz API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.beti.fizz
      vars:
        BUNDLE_ID: "com.beti.fizz"
        XCODE_SCHEME: "BetiFizz"
        APP_STORE_APPLE_ID: 6761179199
      xcode: latest
    scripts:
      - name: Set up provisioning profiles
        script: xcode-project use-profiles
        
      - name: Increment build number
        script: |
          cd "$CM_BUILD_DIR"
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          
      - name: Archive project
        script: |
          # Создаем директорию для архива
          mkdir -p build/ios/xcarchive
          
          # Архивация проекта
          xcodebuild archive \
            -project "BetiFizz.xcodeproj" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "build/ios/xcarchive/BetiFizz.xcarchive" \
            -allowProvisioningUpdates \
            -destination 'generic/platform=iOS'
          
      - name: Export IPA
        script: |
          # Создаем exportOptions.plist
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadSymbols</key>
              <true/>
              <key>stripSwiftSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF
          
          # Экспортируем IPA
          xcodebuild -exportArchive \
            -archivePath "build/ios/xcarchive/BetiFizz.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "build/ios/ipa" \
            -allowProvisioningUpdates
          
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
